### ISSUE TITLE
Apply free build agent

### ISSUE THREAD

**Issue by SarotecK** [SarotecK/chickenhook#15]
Microsoft Azure offers free build agents for opensource projects:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml

Can we have android / linux builds?

Are there other solutions?

**Comment by ZeGerm4n** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops

**Comment by ZeGerm4n** [comment]
if I understand correctly we either need an organization or the owner of the repo has to setup all by his own. We will have to install this for our repo https://github.com/apps/azure-pipelines

**Comment by SarotecK** [comment]
Thanks, I installed it into ChickenHook organzation
