### ISSUE TITLE
How to hook a function which's registered in JNI_ONLOAD?

### ISSUE THREAD

**Issue by owen800q** [SarotecK/chickenhook#25]
I am wondering if any example to show the way to hook a function being register in JNI_ONLOAD function?
By using frida, In order to locate that function pointer being hooked. I need to do something like this
```
var JNI_LOAD_POINTER = Module.getExportByName('libnative.so', 'JNI_OnLoad'); //get absolute JNI_ONLOAD address from memory
// Getting base address by subtraction of relative address of JNI_ONLOAD, supposed it is 0x31A04
var BASE_ADDR = parseInt(JNI_LOAD_POINTER) - parseInt('0x31A04'); 
//The absolute function pointer can be got by adding base address and relative address of hooked function
var hookpointer = '0x' + parseInt(BASE_ADDR + parseInt('0x32168')).toString(16) // 
var pointer = new NativePointer(hookpointer) //

```

**Comment by SarotecK** [comment]
I'll try to write an example in a seperate branch and we can discuss about the scenario I applied then...

**Comment by SarotecK** [comment]
You can have a look into the jni_hook_example.
I hooked the JNI_Env->RegisterNatives function. 
I iterate all JNINativeMethods and manipulate the function pointers.

I'll provide an example with WebView in the Evening.

**Comment by SarotecK** [comment]
I guess you could do the same with frida too right?

**Comment by owen800q** [comment]
> I guess you could do the same with frida too right?

Yes, Frida can do the same, but the frida server is banned by some Chinese brand mobile phones, the interesting thing is the frida detection logics was implemented in system layer not specific app. So far I have no idea how to bypass the tricks.

Although I can use frida on emulator but the problem is many apps do not support x86 emulator.
So I want to try chickenhook on arm platform..

**Comment by SarotecK** [comment]
I didn't know about any device used in europe that has frida detection on system level. Do you wanna tell me which device has this feature?

May they check for names, binary signature or blocked ptrace attach (may you know frida uses ptrace)... 

There are plans for chickenhook to be able to be installed into existing binaries (static hooking) and also to apply the ptrace feature (hook other processes)... But this will take some time...

**Comment by SarotecK** [comment]
I updated the code a lil bit.. may it helps for your purposes!
